### ISSUE TITLE
Show wins/losses by map type

### ISSUE THREAD

**Issue by AkshayRao27** [cheshire137/competiwatch-desktop#51]
If you don't want to make another category for map type, one way to implement this could be: 
1. Group maps by type (so instead of B. World, Busan, Dorado,..., make it B.World, Eichenwalde, Hollywood,...)
2. Add map type under these groups
3. Let the current bars be as they are above the map names.
4. Add the same kind of bars, mirrored, facing downward below map type!

**Comment by cheshire137** [comment]
I like this! Thanks for the idea. Could reinforce peoples opinions about 2CP if they see they don't win as much on 2CP as KotH, for example. 😆
