### ISSUE TITLE
China server

### ISSUE THREAD

**Issue by Ahao096** [cheshire137/competiwatch-desktop#92]
How to view the data of servers in China

**Comment by cheshire137** [comment]
你好！Unfortunately, Blizzard doesn't have an Overwatch API, so Competiwatch doesn't gather data about your games for you. All the data in Competiwatch is just what you log yourself. This means you should be able to log games that you play on Chinese servers in Competiwatch, though.

**Comment by Ahao096** [comment]
ok i know,Thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sarah Vessels"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 凌晨0:19
收件人:&nbsp;"cheshire137/competiwatch-desktop"<competiwatch-desktop@noreply.github.com&gt;;
抄送:&nbsp;"『無所事事』"<380047396@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cheshire137/competiwatch-desktop] China server (#92)





 
你好！Unfortunately, Blizzard doesn't have an Overwatch API, so Competiwatch doesn't gather data about your games for you. All the data in Competiwatch is just what you log yourself. This means you should be able to log games that you play on Chinese servers in Competiwatch, though.
